name: Blog CI/CD

# 触发条件：在 push 到 main 分支后触发
on:
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  blog-cicd:
    name: Hexo blog build & deploy
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache node modules
        # 设置包缓存目录，避免每次下载
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install hexo dependencies
        # 下载 hexo-cli 脚手架及相关安装包
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate files
        # 编译 markdown 文件
        run: |
          hexo clean
          hexo generate
          npm install hexo-generator-sitemap --save
          npm install hexo-generator-baidu-sitemap --save
          npm install hexo-baidu-url-submit --save

#      - name: Sync to Gitee
#        uses: wearerequired/git-mirror-action@master
#        env:
#          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
#          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
#        with:
#          # 注意替换为你的 GitHub 源仓库地址
#          source-repo: git@github.com:lianbian/lianbian.github.io.git
#          # 注意替换为你的 Gitee 目标仓库地址
#          destination-repo: git@gitee.com:lianbian/lianbian.git

#      - name: Build Gitee Pages
#        uses: yanglbme/gitee-pages-action@main
#        with:
#          # 注意替换为你的 Gitee 用户名
#          gitee-username: ${{ secrets.GITEE_USERNAME }}
#          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
#          gitee-password: ${{ secrets.GITEE_PASSWORD }}
#          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
#          gitee-repo: lianbian/lianbian
#          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
#          branch: main

      - name: Deploy hexo blog
        env:
          # Github 仓库
          GITHUB_REPO: github.com/lianbian/lianbian.github.io
        # 将编译后的博客文件推送到指定分支
        run: |
          cd ./public && git init -b gh-pages && git add .
          git config user.name "lianbian"
          git config user.email "ilianbian@163.com"
          git add .
          git commit -m "Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.BLOG_ACCESS_TOKEN }}@$GITHUB_REPO" gh-pages:gh-pages

#      - name: Deploy to Tencent CloudBase
#        uses: TencentCloudBase/cloudbase-action@v2
#        with:
#          secretId: ${{secrets.secret_Id}}
#          secretKey: ${{secrets.secret_Key}}
#          envId: ${{secrets.env_Id}}